INSERT INTO COUPON_DATA VALUES(1, 'Ten Euro', 10, 'Test Terms and Conditions' );
INSERT INTO COUPON_DATA VALUES(2, 'Twenty Euro', 20,'Test Terms and Conditions' );
INSERT INTO COUPON_DATA VALUES(3, 'Fifty Euro', 50, 'Test Terms and Conditions' );
INSERT INTO COUPON_DATA VALUES(4, 'Hundred Euro', 100, 'Test Terms and Conditions' );
commit;

INSERT INTO PROFILE_DATA  (PROFILE_ID, AGE, CATEGORY, EMAIL, FIRST_NAME, LANGUAGE, LAST_NAME, MOBILE_NUMBER, USER_NAME) values (1000, 30, 'PARTNER', 'test@shoppe.com', 'K Market', 'fi', 'K-Market Oy' , '+358 41 567 987', 'kmarket');
INSERT INTO PROFILE_DATA  (PROFILE_ID, AGE, CATEGORY, EMAIL, FIRST_NAME, LANGUAGE, LAST_NAME, MOBILE_NUMBER, USER_NAME) values (1001, 30, 'PARTNER', 'test1@shoppe.com', 'S Market', 'fi', 'S-Market Oy' , '+358 41 567 000', 'smarket');
INSERT INTO PROFILE_DATA  (PROFILE_ID, AGE, CATEGORY, EMAIL, FIRST_NAME, LANGUAGE, LAST_NAME, MOBILE_NUMBER, USER_NAME) values (1002, 35, 'CUSTOMER', 'gayan@shoppe.com', 'Gayan', 'fi', 'Kan' , '+358 41 567 123', 'gayankan');
commit;

INSERT INTO PARTNER_DATA (ID, ADDRESS, LEGAL_NAME, MARKETING_NAME, PROFILE_ID) VALUES (100, 'K-Market Turku', 'K-Market', 'K-Market', 1000);
INSERT INTO PARTNER_DATA (ID, ADDRESS, LEGAL_NAME, MARKETING_NAME, PROFILE_ID) VALUES  (101, 'S-Market Turku', 'S-Market', 'S-Market', 1001);
commit;

INSERT INTO WALLET_DATA (WALLET_ID, BALANCE, PROFILE_ID, CURRENCY) VALUES (1, 100, 1002, 'EUR' );

INSERT INTO PURCHASED_COUPON_DATA(ID, CURRENCY, DISCOUNT_PERCENTAGE, EXPIRY_DATE, PAID, PAID_DATE, PURCHACED_DATE, QR_CODE, RATE, VALID, COUPON_ID, WALLET_ID) VALUES (1, 'EUR' , 10, '2023-12-31', 0, null, '2023-01-01', '123456', 20, 1, 2, 1);
INSERT INTO PURCHASED_COUPON_DATA(ID, CURRENCY, DISCOUNT_PERCENTAGE, EXPIRY_DATE, PAID, PAID_DATE, PURCHACED_DATE, QR_CODE, RATE, VALID, COUPON_ID, WALLET_ID) VALUES (2, 'EUR' , 10, '2023-11-30', 0, null, '2023-02-01', '123456', 50, 1, 3, 1);
commit;

INSERT INTO PAYMENT_DATA (PAYMENT_ID, CARD_NUMBER, PAYMENT_AMOUNT, PAYMENT_GATEWAY, PAYMENT_REFERENCE, TRANSACTION_REFERENCE, PURCHASED_COUPON_ID) VALUES (100, '123456XXXX', 20, 'test', 'test', 'test', 1);
INSERT INTO PAYMENT_DATA (PAYMENT_ID, CARD_NUMBER, PAYMENT_AMOUNT, PAYMENT_GATEWAY, PAYMENT_REFERENCE, TRANSACTION_REFERENCE, PURCHASED_COUPON_ID) VALUES (101, '123456XXXX', 50, 'test', 'test', 'test', 2);
commit;

select * from COUPON_DATA;
select * from PROFILE_DATA;
select * from PARTNER_DATA;
select * from WALLET_DATA;
select * from PURCHASED_COUPON_DATA;
select * from PAYMENT_DATA;




